apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:                                                                                                                                        
    prometheus: k8s
    role: alert-rules
  name: nodelocaldns-k8s-rules
  namespace: monitoring
spec:
  groups:
  - name: nodelocaldns.rules
    rules:
    - alert: NodeLocalDNSDown
      annotations:
        message: NodeLocalDNS has disappeared from Prometheus target discovery.
      expr: |
        absent(up{job="node-local-dns"} == 1)
      for: 15m
      labels:
        severity: critical
    - alert: NodeLocalDNSLatencyHigh
      annotations:
        message: NodeLocalDNS has 99th percentile latency of {{ $value }} seconds for
          server {{ $labels.server }} zone {{ $labels.zone }} .
      expr: |
        histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job="node-local-dns"}[5m])) without(instance, pod)) > 4
      for: 10m
      labels:
        severity: critical
    - alert: NodeLocalDNSErrorsHigh
      annotations:
        message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
          }} of requests.
      expr: |
        sum(rate(coredns_dns_response_rcode_count_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_dns_response_rcode_count_total{job="node-local-dns"}[5m])) > 0.03
      for: 10m
      labels:
        severity: critical
    - alert: NodeLocalDNSErrorsHigh
      annotations:
        message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
          }} of requests.
      expr: |
        sum(rate(coredns_dns_response_rcode_count_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_dns_response_rcode_count_total{job="node-local-dns"}[5m])) > 0.01
      for: 10m
      labels:
        severity: warning
  - name: nodelocaldns_forward.rules
    rules:
    - alert: NodeLocalDNSForwardLatencyHigh
      annotations:
        message: NodeLocalDNS has 99th percentile latency of {{ $value }} seconds forwarding
          requests to {{ $labels.to }}.
      expr: |
        histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{job="node-local-dns"}[5m])) without(instance, pod)) > 4
      for: 10m
      labels:
        severity: critical
    - alert: NodeLocalDNSForwardErrorsHigh
      annotations:
        message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
          }} of forward requests to {{ $labels.to }}.
      expr: |
        sum(rate(coredns_forward_response_rcode_count_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_forward_response_rcode_count_total{job="node-local-dns"}[5m])) > 0.03
      for: 10m
      labels:
        severity: critical
    - alert: NodeLocalDNSForwardErrorsHigh
      annotations:
        message: NodeLocalDNS is returning SERVFAIL for {{ $value | humanizePercentage
          }} of forward requests to {{ $labels.to }}.
      expr: |
        sum(rate(coredns_dns_response_rcode_count_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_dns_response_rcode_count_total{job="node-local-dns"}[5m])) > 0.01
      for: 10m
      labels:
        severity: warning