apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: node-local-dns-prometheus-discovery
  labels:
    k8s-app: node-local-dns
spec:
  selector:
    k8s-app: node-local-dns
  type: ClusterIP
  clusterIP: None 
  ports:
  - name: metrics
    port: 9253
    targetPort: 9253
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-local-dns
  name: node-local-dns
  namespace: kube-system
spec:
  endpoints:
  - interval: 10s
    port: metrics
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: node-local-dns